### ISSUE TITLE
Wrong year indicated when using "ante kalendas" dates in decemer

### ISSUE THREAD

**Issue by mgoellnitz** [xavierfreyburger/tempus-romanum#3]
tempora Decembris, qui ante kalendis proximis sunt, annum malum indicant.

![photo_2020-12-27_22-45-36](https://user-images.githubusercontent.com/432458/103180381-8b571880-4895-11eb-8ec2-7b5950c8cbab.jpg)

**Comment by xavierfreyburger** [comment]
Thanks for posting this issue ! It's solved in the new release (2.2.4).
