### ISSUE TITLE
Tempus Romanum Font

### ISSUE THREAD

**Issue by IndomitableAlbus** [xavierfreyburger/tempus-romanum#4]
Hi Dev.Sorry to post here, I couldn't find any contact details in the App.

The Apps great and working well.

Please could you tell me what font you have used, as Im trying to match an element on my home page.

I extracted the App and looked in resources but found no font.

Thank you

**Comment by xavierfreyburger** [comment]
Hi,

I used the default "serif" Android font, I think it's name is "Roboto Serif".
Have a look [here](https://fonts.google.com/specimen/Roboto+Serif?query=roboto+serif&preview.text=Est%20dies%20Martis%20pridie%20nonas%20iunias%20MMDCCLXXVII%20ab%20Urbe%20condita.) 😉

Hope it helps.
